[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "firebase-admin>=6.6.0",
    "flask>=3.1.0",
    "pytz>=2025.1",
]
